### ISSUE TITLE
Change in Line 308 of transition.R

### ISSUE THREAD

**Issue by cdueben** [AgrDataSci/gdistance#1]
Dear package authors,

When submitting this suggestion as a pull request to cran/gdistance a while ago I did not notice the message pointing to this site. Thus, I hereby re-submit my comment concerning a bug in transition().

Raster bricks with NA values produce errors.

Reproducable example:
```
directions <- 8
x <- raster(matrix(data = c(NA, 20, 7, NA, NA, 18, NA, 5, 1, 21, 3, 15, 22, 17, 12, 14), nrow = 4, ncol = 4, byrow = T))
y <- raster(matrix(data = c(690, NA, 673, 442, 750, 620, 680, 491, 467, NA, 624, 590, NA, NA, 727, 462), nrow = 4, ncol = 4, byrow = T))
x <- brick(x, y)
xy <- cbind(1:ncell(x),getValues(x))
xy <- na.omit(xy)
dataCells <- xy[,1]
adj <- adjacent(x, cells=dataCells, pairs=TRUE, target=dataCells, directions=directions)
x.minus.y <- xy[adj[,1],-1]-xy[adj[,2],-1]
Error in xy[adj[, 1], -1] : subscript out of bounds
```

I therefore suggest to replace "x.minus.y <- xy[adj[,1],-1]-xy[adj[,2],-1]" in line 308 with "x.minus.y <- getValues(x)[adj[,1],] - getValues(x)[adj[,2],]".

Kind regards,
Christian Düben

**Comment by kauedesousa** [comment]
Hi @ChristianDueben sorry for the late reply. I accidentally pressed the option of not getting news from this repo and I missed this issue. Sorry about that. 

I will adjust accordingly 

Thanks! 

K

**Comment by kauedesousa** [comment]
Hi @ChristianDueben I added your suggestion to gdistance v1.3-2. Soon it will be on CRAN

**Comment by cdueben** [comment]
Thanks, @kauedesousa .
