### ISSUE TITLE
email to movecost maintainer

### ISSUE THREAD

**Issue by rsbivand** [AgrDataSci/gdistance#11]
It appears that the CRS of maungawhau.grd is outdated (I'm checking all 1100 packages using the external PROJ library through sp/rgdal/raster, etc.). Adding 

`raster::crs(volc) <- sp::CRS("+init=epsg:27200")`

after the import line 

`volc <- raster::raster(system.file("external/maungawhau.grd", package="gdistance"))`

in movebound.Rd (and other help files using the same imported data) should help -  the failure was in raster::compareRaster(accum_final, dtm). An upstream solution would also be to regenerate the grd file, The WKT2 representation is secure going forward, the proj4 string datum representation is defunct for PROJ > 5 (PROJ 9 will be released shortly). If in the grd file it is sufficient to  keep a proj4 string, it should probably be: `+proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +units=m +no_defs`.

I'm checking with PROJ 9.0.0RC1, GDAL 3.5.0dev HEAD, development versions of sp and rgdal, so this problem has not showed up elsewhere yet, I think.

**Comment by rsbivand** [comment]
Please take urgent action to correct this; movecost is now failing on CRAN checks with PROJ 9.

**Comment by kauedesousa** [comment]
Hi @rsbivand Thanks for reporting the issue and sorry for the long silent. I fixed it it here https://github.com/AgrDataSci/gdistance/commit/0fb2e6316df5747413a507f5ce13323a04d6e2de and I am checking another issue before sending to CRAN. If I don't fix the other issue until tomorrow I will send just with this fix for the sake of not breaking movecost

**Comment by rsbivand** [comment]
I think no rush, as the **movecost** maintainer made the object into an `RDA` to load as `data()`, but didn't correct the CRS before doing so. When it then failed CRAN tests, I sent the movecost maintainer an `RDA` file including the CRS update.

**Comment by rsbivand** [comment]
See also email to **leastcostpath** maintainer (you may see these errors in reverse dependency checks for **gdistance**):

> You will have seen many CRAN check errors at
https://cran.r-project.org/web/checks/check_results_leastcostpath.html.

> I encountered the same in reverse dependency testing. I first thought that
this was related to https://github.com/AgrDataSci/gdistance/issues/11 as you
use the same data.

> I added raster::crs(volc) <- sp::CRS("+init=epsg:27200") at line 53 in
leastcostpath-1.Rmd, but this did not resolvve the problem (but maybe
contributed to it).

> Resolution for me came from setting  the RNG seed in line 128 set.seed(1)
before sp::spsample(). With these additions, the package passes R CMD check
on a platform similar to those now failing. I think  that differences in
PROJ and GDAL versions may underlie the differences, but possibly also
differences in raster in its development version.

**Comment by andrewmarx** [comment]
It appears this is no longer an issue? If it is, feel free to reopen or start a new issue

**Comment by rsbivand** [comment]
Right, `gdistance` CMD checks OK for me in relevant scenarios.
