### ISSUE TITLE
Handle mantainance to Andrew Marx

### ISSUE THREAD

**Issue by kauedesousa** [AgrDataSci/gdistance#18]
gdistance will be maintained by @andrewmarx. 

1. Change DESCRIPTION file 
2. Try to solve current issues 
3. Prepare pkg for new release
4. Communicate CRAN

**Comment by andrewmarx** [comment]
I probably wouldn't make 2 part of this; about half the issues might disappear with a rewrite to terra and new transition code. But before doing that, I would like to get the package updated on CRAN, which I will work on now.

Also, would you have any concerns about renaming the master branch to main?

**Comment by andrewmarx** [comment]
CRAN has accepted version 1.6.2 of the package with the updated maintainership, so I'm going to go ahead and close this.
