### ISSUE TITLE
Fix last code chunk in Overview vignette

### ISSUE THREAD

**Issue by andrewmarx** [AgrDataSci/gdistance#19]
`pathInc()` in last code chunk of Overview vignette produces a matrix decomposition error. Need to identify source of problem and undo the workaround in commit [70c9656](https://github.com/AgrDataSci/gdistance/commit/70c96563e7955d2663e412d54b09ea1d3b787fc4)

**Comment by DemetriosG** [comment]
Would it be realistic to expect that the updated versions of transition() and geocorrection() will be able to handle, say, 500M cells? The last version released by Kaue, before you graciously agreed to take over, produces wrong accCost() results when either the # of columns or the # of rows of the impedance raster exceed 10,000. At 500M cells, the limit would increase to 22300+ cells, sufficiently large for a set of pressing problems that have been put on hold.
Many thanks for your efforts.

**Comment by andrewmarx** [comment]
This isn't really the correct issue to be discussing that, but I do plan to make sure that whatever issue is happening in #17 is resolved.

**Comment by andrewmarx** [comment]
Closing as "fixed" for now. See commit 305f1b9 for details
