### ISSUE TITLE
Dealing with ties

### ISSUE THREAD

**Issue by lroich** [AgrDataSci/gdistance#23]
The command `shortestPath()` does not seem to return as output _all_ the relevant least cost paths connecting two endpoints. To clarify the issue, hereby I create a toy raster and then I compute the least cost path between two endpoints. From the toy example and the related figure hereby, one can see that two least cost paths would be normally expected: one passing to the east and another to the west of a central higher-cost cell. However, only one of such least cost paths is returned as output.

This issue may be particularly relevant when artificial rasters are used to run simulations, precisely because cost heterogeneity across raster cells might be especially limited in such cases. So, the command `shortestPath()` should at least allow for an optional argument indicating whether all LCPs are to be returned in the output or only one of them.

In terms of the current code, this would correspond to calculating LCPs with the command `all_shortest_paths()` instead of the current `get.shortest.paths()`. 

![image](https://github.com/AgrDataSci/gdistance/assets/159818923/970ccdb8-a5d4-48f3-b02a-e0a40b4d59b5)

`
library(sf)
library(terra)
library(rgdal) #version 1.6-7
library(rgeos) #version 0.6-4
library(gdistance)
library(sp)
library(raster)

# From cost matrix to transition layer 
x0 <- c(1510969,4344218) #projected coordinates in EPGS:3003
nr <- 3
nc <- 3
cost.m <- matrix(data = c(1,1,1,1, 3,1,1,1,1), nrow = nr, ncol = nc, byrow = T)
cost.r <- rast(cost.m, extent = ext(c(x0[1],x0[1]+nc,x0[2],x0[2]+nr)), crs = "EPSG:3003")
conductance.r <- 1/cost.r
conductance.tr <- gdistance::transition(raster(conductance.r), transitionFunction = mean, directions = 8, symm = T) %>% gdistance::geoCorrection(type = "c",multpl = F)
image(transitionMatrix(conductance.tr), main = "Transition layer")

# Obtain polygons, centroids, and endpoints from raster cells
pgn <- as.polygons(conductance.r, aggregate = F, na.rm = T, na.all = T) %>% st_as_sf()
ctr <- st_centroid(pgn)
endpts <- as(ctr[c(2,8) ,],"Spatial")

# Obtain and plot least cost path(s)
lcps <- gdistance::shortestPath(
  conductance.tr,
  endpts[1,],
  endpts[2,],
  "SpatialLines")
crs(lcps) <- crs(as(endpts,"Spatial"))

plot(cost.r, colNA = NA, axes = F, box = F, legend = T)
plot(st_geometry(pgn), border = "white", lwd = 0.2, add = T)
plot(st_as_sfc(lcps), col = "black", lwd = 2, axes = F, add = T)
plot(st_as_sfc(endpts), pch = 16, cex = 1, col = "black", axes = F, add = T)
`

**Session Info**
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8 
[2] LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Europe/Rome
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] gdistance_1.6.4 Matrix_1.6-1.1  igraph_2.0.1.1  raster_3.6-26  
 [5] rgeos_0.6-4     rgdal_1.6-7     terra_1.7-71    sf_1.0-15      
 [9] this.path_2.3.1 sp_2.1-3       

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5        cli_3.6.2          rlang_1.1.3       
 [4] DBI_1.2.1          KernSmooth_2.23-22 generics_0.1.3    
 [7] glue_1.7.0         e1071_1.7-14       fansi_1.0.6       
[10] grid_4.3.2         tibble_3.2.1       classInt_0.4-10   
[13] lifecycle_1.0.4    compiler_4.3.2     dplyr_1.1.4       
[16] codetools_0.2-19   sessioninfo_1.2.2  Rcpp_1.0.12       
[19] pkgconfig_2.0.3    rstudioapi_0.15.0  lattice_0.22-5    
[22] R6_2.5.1           tidyselect_1.2.0   utf8_1.2.4        
[25] class_7.3-22       pillar_1.9.0       magrittr_2.0.3    
[28] tools_4.3.2        proxy_0.4-27       units_0.8-5

**Comment by andrewmarx** [comment]
Looking back through the history of `shortestPath()` function, it looks like it never did this; it always returned a single shortest path for a given `origin` and `goal`. Instead, the function was designed so that you could specify multiple pairs of points (with the caveat that only the first `origin` would be used) and that that would return multiple paths. So it's not a bug, per se. It may be something that could be implemented in the future as a new function, but it'd be a low priority. If it's something you need now, you can take the first part of the [`shortestPath()`](https://github.com/AgrDataSci/gdistance/blob/4076198439cc7126c2662f5ebac50ec7e55110f9/R/shortestPath.R#L68-L91) function and modify it to use [`all_shortest_paths()`](https://igraph.org/r/doc/distances.html) instead of `get.shortest.paths()`. 

On a side note, the packages *rgeos* and *rgdal* are deprecated and removed from CRAN. Fortunately, they are unnecessary for any of the code you provided
