### ISSUE TITLE
Question about correcting for grid distortion when using non lat/long rasters

### ISSUE THREAD

**Issue by CCheCastaldo** [AgrDataSci/gdistance#5]
Hi @kauedesousa, 

I was wondering if you had any advice on using gdistance to correct for grid distortion on rasters projected in some CRS other than lat/long grids?  

I am using the gdistance package to compute shortest path distances between cells on a grid projected in south polar stereographic (epsg 3031). The grid has a single fixed start cell and the remaining cells are a mix of land cells (cell value = 1) and water cells (cell value = NA), where land cells block movement through water. I use costDistance() to calculate the shortest water-only path distance to each water cell from the start cell.  According to the documentation, geoCorrection() will correct (I think) for 1) longer diagonal moves vs. orthogonal ones and 2) grid distortion in the EW direction only using `type = c` and both the EW and NS direction using `type = r`, but it was unclear how it handles non lat/long rasters. To check this, I ran the following code on my 3031 land/water raster:

```
water_grid_t <- gdistance::transition(water_land_grid, mean, directions = 8)
tm_not_grid_corrected  <- gdistance::geoCorrection(water_grid_t, scl = FALSE, type = "c")
```
Applying geoCorrection() to the transition matrix, the conductance values for diagonal moves are appropriately adjusted. However, the transition matrix only uses two conductance values (one for orthogonal moves and one for diagonal moves). These are constant across the matrix, implying that there is no correction for the grid distortion (same result with setting `type = r`). In south polar stereographic, distance is preserved at 71 S latitude and NS and EW planar distance becomes increasingly distorted as you move away in either direction (planar distances are too large as you go north to the equator and too small as you go south to the pole, compared to their corresponding great circle distances). This grid distortion affects shortest path calculations in different scenarios. One example is if you are approaching an obstacle (such as a single cell island) from EW and you wish to get to a cell on the opposite side. Ignoring distortion, both paths around the island are equally cost-effective as this is just 2 diagonal moves on a planar grid. However, in reality these distances are not equal, and the discrepancy between a northern vs southern detour (at least in south polar stereographic) depends on whether the obstacle is above or below 70 S latitude and how far from this latitude of true origin.

The solution I cam up with was to correct for grid distortion by replacing the mean function in transition() with one that calculates the reciprocal of the great circle distance between neighboring cells. This had the effect of correcting for both grid distortion and the differences between diagonal vs. orthogonal moves all at once, meaning there was no reason to then geocorrect() afterwards. Testing this out, the distances calculated with costDistance() using this transition matrix appear to be the sum of the great circle distances between each cell to cell move along the shortest path from A to B. I was wondering if you thought this was a reasonable approach to solving the problem.

```
library(sf)
cell_num_grid <- water_land_grid
values(cell_num_grid) <- 1:ncell(cell_num_grid) 
grid_pts <- data.frame(xyFromCell(water_land_grid, 1:ncell(water_land_grid), spatial = FALSE))
grid_pts_sf <- st_as_sf(grid_pts, coords = c("x", "y"), crs = 3031) %>% st_transform(4326)
gcd_func <- function(x) {
  1 / as.numeric(st_distance(grid_pts_sf[x[1],], grid_pts_sf[x[2],]))
}
tm <- gdistance::transition(cell_num_grid, gcd_func, directions = 8)
barrier_tm <- gdistance::transition(water_land_grid, mean, directions = 8)
tm_grid_corrected <- tm * barrier_tm
```

Thanks for any suggestions and for all the hard work you have put into this fantastic package. I apologize in advance if I am being obtuse about all this. 

Sincerely,

Christian Che-Castaldo

**Comment by andrewmarx** [comment]
Not sure this is relevant anymore after almost 3 years, so I'm going to go ahead and close it.

I will say that the geocorrection does not consider the `type` argument when the raster is anything other than lon/lat. It only considers the point distance between the pixels: https://github.com/AgrDataSci/gdistance/blob/7c2066b7c2526e3abfb30eee39f33b793ccbaaa0/R/geoCorrection.R#L140-L154

**Comment by CCheCastaldo** [comment]
Thanks Andrew
