### ISSUE TITLE
Broken link in CRAN page

### ISSUE THREAD

**Issue by damianooldoni** [AgrDataSci/gdistance#6]
Hi. While trying to retrieve documentation of this package, I noticed that the URL field https://agrobioinfoservices.github.io/gdistance/ in CRAN official page (https://cran.r-project.org/web/packages/gdistance/) doesn't exists. It seems that this repo doesn't have a GitHub page anymore.

**Comment by kauedesousa** [comment]
Thanks @damianooldoni 

We changed the account name a week ago and we are moving to update the links and packages' documentation.

K
